import { MethodClear } from './stubs/clear.test';
import { MethodClone } from './stubs/clone.test';
import { MethodConcat } from './stubs/concat.test';
import { MethodEntries } from './stubs/entries.test';
import { MethodEvery } from './stubs/every.test';
import { MethodFill } from './stubs/fill.test';
import { MethodFillDynamic } from './stubs/fillDynamic.test';
import { MethodFilter } from './stubs/filter.test';
import { MethodFind } from './stubs/find.test';
import { MethodFindIndex } from './stubs/findIndex.test';
import { MethodFlat } from './stubs/flat.test';
import { MethodFlatMap } from './stubs/flatMap.test';
import { MethodForEach } from './stubs/forEach.test';
import { MethodIncludes } from './stubs/includes.test';
import { MethodIndexOf } from './stubs/indexOf.test';
import { MethodInsertAfter } from './stubs/insertAfter.test';
import { MethodInsertBefore } from './stubs/insertBefore.test';
import { MethodJoin } from './stubs/join.test';
import { MethodLastIndexOf } from './stubs/lastIndexOf.test';
import { MethodMap } from './stubs/map.test';
import { MethodPeek } from './stubs/peek.test';
import { MethodPeekAt } from './stubs/peekAt.test';
import { MethodPeekLast } from './stubs/peekLast.test';
import { MethodPop } from './stubs/pop.test';
import { MethodPush } from './stubs/push.test';
import { MethodReduce } from './stubs/reduce.test';
import { MethodReduceRight } from './stubs/reduceRight.test';
import { MethodRemoveAt } from './stubs/removeAt.test';
import { MethodRemoveRange } from './stubs/removeRange.test';
import { MethodReverse } from './stubs/reverse.test';
import { MethodShift } from './stubs/shift.test';
import { MethodSome } from './stubs/some.test';
import { MethodSort } from './stubs/sort.test';
import { MethodTake } from './stubs/take.test';
import { MethodToString } from './stubs/toString.test';
import { MethodUnshift } from './stubs/unshift.test';
import { MethodUpdate } from './stubs/update.test';
import { MethodValues } from './stubs/values.test';

describe('Methods', () => {
  MethodClear();
  MethodClone();
  MethodConcat();
  MethodEntries();
  MethodEvery();
  MethodFill();
  MethodFillDynamic();
  MethodFilter();
  MethodFind();
  MethodFindIndex();
  MethodFlat();
  MethodFlatMap();
  MethodForEach();
  MethodIncludes();
  MethodIndexOf();
  MethodInsertAfter();
  MethodInsertBefore();
  MethodJoin();
  MethodLastIndexOf();
  MethodMap();
  MethodPeek();
  MethodPeekAt();
  MethodPeekLast();
  MethodPop();
  MethodPush();
  MethodReduce();
  MethodReduceRight();
  MethodRemoveAt();
  MethodRemoveRange();
  MethodReverse();
  MethodShift();
  MethodSome();
  MethodSort();
  MethodTake();
  MethodToString();
  MethodUnshift();
  MethodUpdate();
  MethodValues();
});
